### ISSUE TITLE
Change Twitter account

### ISSUE THREAD

**Issue by jhurtadojerves** [Shade-/MyTwitter-Connect#13]
Hello, before swim, say I really like the plugin.

I have a question. Is there a way to decouple the Twitter account of a user?

I mean, for example, in the forum I have linked my main Twitter account, but I would change my secondary account you can?

PD: Sorry for my bad English

**Comment by JulioHurtado** [comment]
I still have the same problem.

I uninstalled the plugin, I went to download it, I went to install it. I added the variable you mention, but I still have the same problem as before.

PD: Sorry for bad English

**Comment by JulioHurtado** [comment]
Problema Solved: https://github.com/Shade-/MyTwitter-Connect/pull/14
