### ISSUE TITLE
No options in User CP

### ISSUE THREAD

**Issue by marcandrews** [Shade-/MyTwitter-Connect#15]
The options for Twitter integration (like those for MyFacebook Connect) are missing from the User CP. Any ideas on how to get the Twitter integration User CP options to show so that registered forum users can link their forum account with Twitter?

**Comment by kimwowboom** [comment]
Experienced the same problem

**Comment by marcandrews** [comment]
I found the fix [here](http://community.mybb.com/thread-138202-post-1078706.html#pid1078706).

Find
```php
if ($settings['mytwconnect_enabled']) {
```

Replace with
```php
if ($mybb->settings['mytwconnect_enabled']) {
```

**Comment by kimwowboom** [comment]
It's already like that in current script.

**Comment by marcandrews** [comment]
If you grabbed the version from MyBB Extend, this version may not be the latest.

**Comment by marcandrews** [comment]
It is fixed in the [master branch](https://github.com/Shade-/MyTwitter-Connect/blob/master/inc/plugins/mytwconnect.php#L233) but [2.0.1](https://github.com/Shade-/MyTwitter-Connect/blob/2.0.1/inc/plugins/mytwconnect.php#L231) **does not** have this fix included
