### ISSUE TITLE
Why is the Twitter option missing in usercp?

### ISSUE THREAD

**Issue by johnnyvang** [Shade-/MyTwitter-Connect#17]
I have all MY connect plugins and they all work great.
But i only see Facebook an G+ as option in the usercp and not Twitter.
Using the link(s) usercp.php?action=mygpconnect or usercp.php?action=myfbconnect works.
Only using the link usercp.php?action=mytwconnect.
This link is in one of the files.
Google and Facebook shows me a few options, but Twitter shows me a blanc page.
I use the download from here and also from MyBB with the same twitter result.
What am i missing or what is missing in the files of the download?
Realy want twitter works the same way as the other 2 do.

**Comment by johnnyvang** [comment]
Found out the problem.
The .zip on MyBB was older then the .zip here :)
Problem solved.

**Comment by Shade-** [comment]
Ops. Might have forgotten to update the MyBB package. Thank you for your report!
