### ISSUE TITLE
Mybb 1.8 Compatibility

### ISSUE THREAD

**Issue by ErikThiart** [Shade-/MyTwitter-Connect#18]
Hello, does this plug in work with mybb 1.8 also is this plugin still maintained and up to date?

**Comment by Shade-** [comment]
MTC hasn't been updated in a while but should work fine AFAIK. It's a stable release so no updates are urgent.

**Comment by ErikThiart** [comment]
Was more concerned with Twitters ever changing API.

Is there anything on the plugin you need help with I have some free time this festive season, I can also help with translations.

I like your plugin so do not mind helping out if you ever need it.
