### ISSUE TITLE
Additional required fields

### ISSUE THREAD

**Issue by kimwowboom** [Shade-/MyTwitter-Connect#4]
What if there are additional required fields in the normal registration settings. Are they added to the Twitter sign up page to?

**Comment by JulioHurtado** [comment]
Problema solucionado: https://github.com/Shade-/MyTwitter-Connect/pull/14

**Comment by Shade-** [comment]
This has been developed exclusively for [Flyover](https://www.mybboost.com/thread-release-flyover-1-3).
